#include <bridge.h>
#include <tim.h>
#include <gpio.h>

void bridgeLeft()
{
	HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_3); //LEFT HIGH
    HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_4); //RIGHT HIGH

	HAL_GPIO_WritePin(BRIDGE1_LEFT_LOW_GPIO_Port, BRIDGE1_LEFT_LOW_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(BRIDGE1_RIGHT_LOW_GPIO_Port, BRIDGE1_RIGHT_LOW_Pin, GPIO_PIN_RESET);
}

void bridgeRight()
{
	HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_3); //LEFT HIGH
	HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_4); // RIGHT HIGH

	HAL_GPIO_WritePin(BRIDGE1_LEFT_LOW_GPIO_Port, BRIDGE1_LEFT_LOW_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(BRIDGE1_RIGHT_LOW_GPIO_Port, BRIDGE1_RIGHT_LOW_Pin, GPIO_PIN_SET);
}

void bridgeOff(void)
{
	HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_3);
	HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_4);

	HAL_GPIO_WritePin(BRIDGE1_LEFT_LOW_GPIO_Port, BRIDGE1_LEFT_LOW_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(BRIDGE1_RIGHT_LOW_GPIO_Port, BRIDGE1_RIGHT_LOW_Pin, GPIO_PIN_SET);
}
